apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  labels:
    grafana_alert: "1"
data:
  contactpoints.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: ntfy
        receivers:
          - uid: ntfy
            type: webhook
            settings:
              url: https://ntfy.vpn.lab.com/channel-general?template=grafana
              httpMethod: POST
            disableResolveMessage: false
  policies.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: ntfy
        group_by:
          - grafana_folder
          - alertname
  alerts.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: kubernetes-int
        folder: Alerts
        interval: 10s
        rules:
          - uid: pod-not-running-int
            title: Pod Not Running (int)
            condition: C
            for: 0m
            data:
              - refId: A
                datasourceUid: victoriametrics-int
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by (namespace, pod) (kube_pod_status_phase{phase!~"Running|Succeeded", namespace!="kube-state-metrics"} == 1)
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      query:
                        params: [B]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: warning
            annotations:
              summary: "K3S-INT: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running"


          - uid: pod-crash-looping-int
            title: Pod Crash Looping (int)
            condition: C
            for: 2m
            data:
              - refId: A
                datasourceUid: victoriametrics-int
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by (namespace, pod, container) (kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace!="kube-state-metrics"}[1m]) == 1
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      query:
                        params: [B]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: warning
            annotations:
              summary: "K3S-INT: Pod {{ $labels.pod }} in {{ $labels.namespace }} is crash looping"
              
          - uid: pod-oomkilled-int
            title: Pod OOMKilled (int)
            condition: C
            for: 0m
            data:
              - refId: A
                datasourceUid: victoriametrics-int
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by(namespace, pod, container) (last_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace!="kube-state-metrics"})) == 1
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      query:
                        params: [B]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: critical
            annotations:
              summary: "K3S-INT: Pod {{ $labels.pod }} container {{ $labels.container }} in {{ $labels.namespace }} was OOMKilled"

      - orgId: 1
        name: kubernetes-ext
        folder: Alerts
        interval: 10s
        rules:
          - uid: pod-not-running-ext
            title: Pod Not Running (ext)
            condition: C
            for: 0m
            data:
              - refId: A
                datasourceUid: victoriametrics-ext
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by (namespace, pod) (kube_pod_status_phase{phase!~"Running|Succeeded", namespace!="kube-state-metrics"} == 1)
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      query:
                        params: [B]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: warning
            annotations:
              summary: "K3S-EXT: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running"
          
          - uid: pod-crash-looping-ext
            title: Pod Crash Looping (ext)
            condition: C
            for: 0m
            data:
              - refId: A
                datasourceUid: victoriametrics-ext
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by (namespace, pod, container) (kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace!="kube-state-metrics"}[1m]) == 1
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [ 0 ]
                      query:
                        params: [ B ]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: warning
            annotations:
              summary: "K3S-EXT: Pod {{ $labels.pod }} in {{ $labels.namespace }} is crash looping"
                
          - uid: pod-oomkilled-ext
            title: Pod OOMKilled (ext)
            condition: C
            for: 0m
            data:
              - refId: A
                datasourceUid: victoriametrics-ext
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  expr: max by (namespace, pod, container) (kube_pod_container_status_last_terminated_reason{reason="OOMKilled", namespace!="kube-state-metrics"}) == 1
                  refId: A
              - refId: B
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: reduce
                  refId: B
                  expression: "A"
                  reducer: last
                  settings:
                    mode: dropNN
              - refId: C
                datasourceUid: "__expr__"
                relativeTimeRange:
                  from: 300
                  to: 0
                model:
                  type: threshold
                  refId: C
                  expression: "B"
                  conditions:
                    - evaluator:
                        type: gt
                        params: [ 0 ]
                      query:
                        params: [ B ]
            noDataState: OK
            execErrState: Alerting
            labels:
              severity: critical
            annotations:
              summary: "K3S-EXT: Pod {{ $labels.pod }} container {{ $labels.container }} in {{ $labels.namespace }} was OOMKilled"