namespace: grafana

resources:
  - ../../base/grafana/
  - namespace.yaml
  - httproute.yaml
  - datasources.yaml
  - dashboards.yaml
  - dashboards-traefik.yaml
  - dashboard-crowdsec.yaml
  - dashboard-truenas.yaml
  - dashboard-proxmox.yaml
  - dashboard-authelia.yaml
  - dashboard-blocky.yaml
  - secrets.yaml
  - alerting.yaml
  - pvc.yaml
  - svc-blocky-proxy.yaml

# Create a service user for ext cluster basic auth in flux/apps/ext/authelia/users-database.yaml, if not yet.
#
# victoria-ext-service-account:
#    displayname: "Victoria Ext Service Account"
#    password: <hash> (use bcrypt)
#    email: victoria-ext-service-account@lab.com
#    groups:
#      - victoria-ext
#      - service

patches:
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
      spec:
        template:
          spec:
            containers:
              - name: grafana
                env:
                  - name: GF_SERVER_ROOT_URL
                    value: "https://grafana.vpn.lab.com"
                  - name: GF_SECURITY_ADMIN_USER
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-user
                  - name: GF_SECURITY_ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-password
                  - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
                    value: /tmp/dashboards/kubernetes-pods.json
                  - name: GF_PLUGINS_PREINSTALL
                    value: victoriametrics-metrics-datasource,victoriametrics-logs-datasource
                  - name: GF_PLUGINS_DISABLE_PLUGINS
                    value: grafana-lokiexplore-app,grafana-pyroscope-app,grafana-metricsdrilldown-app,grafana-exploretraces-app
                  - name: GF_CLOUD_MIGRATION_ENABLED
                    value: "false"
                  - name: GF_FEATURE_TOGGLES_provisioning
                    value: "false"
                  - name: GF_FEATURE_TOGGLES_dashgpt
                    value: "false"
                  - name: GF_FEATURE_TOGGLES_featureHighlights
                    value: "false"
                  - name: GF_FEATURE_TOGGLES_splashScreen
                    value: "false"
                volumeMounts:
                  - name: victoria-ext-auth
                    mountPath: /etc/grafana/secrets/victoria-ext-auth
                    readOnly: true
                  - name: alerting-provisioning
                    mountPath: /etc/grafana/provisioning/alerting
                    readOnly: true
                  - name: plugins
                    mountPath: /var/lib/grafana/plugins
              - name: grafana-sc-dashboard
                env:
                  - name: REQ_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-user
                  - name: REQ_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-password
              - name: grafana-sc-datasources
                env:
                  - name: REQ_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-user
                  - name: REQ_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: grafana-admin
                        key: admin-password
            volumes:
              - name: victoria-ext-auth
                secret:
                  secretName: victoria-ext-auth
              - name: alerting-provisioning
                configMap:
                  name: grafana-alerting
              - name: plugins
                persistentVolumeClaim:
                  claimName: grafana-plugins
