---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grimmory-books-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#books#grimmory"
    volumeAttributes:
      source: "//truenas.lan/books"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: grimmory-books-pv
  storageClassName: ""
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  labels:
    app.kubernetes.io/name: grimmory
    app.kubernetes.io/instance: grimmory
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi