---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-storage-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
