apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-repositories-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#private/git-repos/repositories#forgejo"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/private/git-repos/git
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#private/git-repos/data#forgejo"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/private/git-repos/forgejo
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: forgejo-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-repositories-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: forgejo-repositories-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-db-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
