resources:
  - manifest.readonly.yaml
  - namespace.yaml

patches:
  - target:
      kind: StatefulSet
      name: victoria-logs-victoria-logs-single-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/5
        value: --retentionPeriod=14d
