apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-downloads-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#downloads#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/downloads"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-music-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#music#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/music"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-movies-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#movies#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/movies"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-private-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#private#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/private"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-tvs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#series#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/series"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-games-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#games#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/games"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-videos-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#videos#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/videos"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-special-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#special#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/special"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-books-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#books#filebrowser"
    volumeAttributes:
      source: "//truenas.lan/books"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-downloads-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-music-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-movies-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-private-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-tvs-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-games-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-videos-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: special-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-special-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-books-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
