apiVersion: v1
kind: PersistentVolume
metadata:
  name: radicale-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#private/radicale/data#radicale"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/private/radicale/data
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radicale-private-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#private/radicale#radicale"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/private/radicale
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: radicale-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-private-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: radicale-private-pv
  storageClassName: ""
