---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headplane
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headplane
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: headplane
  apiGroup: rbac.authorization.k8s.io