prometheus:
  enable: true
  path: /metrics

upstreams:
  groups:
    default:
      - 46.182.19.48
      - 80.241.218.68
      - tcp-tls:fdns1.dismail.de:853
      - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
ports:
  dns: 53
  http: 4000

customDNS:
  customTTL: 60s
  filterUnmappedTypes: true
  mapping:
    # a very important one
    vpn.lab.com: 100.64.0.11,fd7a:115c:a1e0::b
    # this is just to make home network hosts like OpenWRT or Fritzbox available from the same LAN when Blocky DNS is used
    openwrt.lan: 192.168.1.1
    fritz.box: 192.168.178.1