---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-data-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce