---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s-volumes-bp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#k3s-volumes-bp#restic"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/k3s-volumes-bp
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-volumes-bp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: k3s-volumes-bp-pv
  storageClassName: ""