apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd-music-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#music#slskd"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/music
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd-books-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#books#slskd"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/books
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd-downloads-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "pve.lan#downloads#slskd"
    volumeAttributes:
      server: pve.lan
      share: /nethescurial/downloads
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: slskd-downloads-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: slskd-music-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: slskd-books-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
