---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-videos-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""  # Must match PVC (empty string for static binding)
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#videos#stash" # smb server host + # + share name + # + app name, must be unique
    volumeAttributes:
      source: "//truenas.lan/videos"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-special-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""  # Must match PVC (empty string for static binding)
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "truenas.lan#special#stash" # smb server host + # + share name + # + app name, must be unique
    volumeAttributes:
      source: "//truenas.lan/special"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: stash-videos-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: special-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: stash-special-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce