[global]
  p: 80               # Listen on port 80
  shr: /shared        # Shared folder path
  hist: /cfg/hists/   # History/log directory
  xvol                # do not follow symlinks outside the volume

  xff-src: lan
  urlform: get        # disable "send msg to srv log" feature

  xff-hdr: X-Forwarded-For
  rproxy: 1

  usernames           # always require a username to log in, not just password
  no-robots           # prevent search engines from scraping data

  bname: HOMELAB /
  doctitle: HOMELAB
  theme: 6
  favico: \ud801\udd63 fff 000
  spinner:            # don't show any spinner
  ui-filesz: 4
  localtime
  rotf-tz: Europe/Berlin
  grid                # show files in grid by default
  ui-norepl           # hides eval button
  ui-nosrvi           # hide server info
  nb                  # hide "powered by"


  % /cfg/users-database.conf     # included file must have "[accounts]" as a first line

[/]
  /srv
  accs:
    rda: user01

[/downloads]
  /srv/downloads
  accs:
    rwmda: user01

[/music]
  /srv/music
  accs:
    rwmda: user01

[/movies]
  /srv/movies
  accs:
    rwmda: user01

[/private]
  /srv/private
  accs:
    rwmda: user01

[/tvs]
  /srv/tvs
  accs:
    rwmda: user01

[/games]
  /srv/games
  accs:
    rwmda: user01

[/videos]
  /srv/videos
  accs:
    rwmda: user01

[/special]
  /srv/special
  accs:
    rwmda: user01

[/books]
  /srv/books
  accs:
    rwmda: user01