---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  annotations:
    k8up.io/backup: "true"
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  annotations:
    k8up.io/backup: "true"
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
